# Generated by Django 3.2.8 on 2022-02-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='traveldb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Location', models.CharField(max_length=200, null=True)),
                ('photo', models.ImageField(default=0, upload_to='image')),
                ('price', models.IntegerField(null=True)),
            ],
        ),
    ]
