# Generated by Django 3.2.8 on 2022-02-10 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveldb',
            old_name='Location',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='traveldb',
            old_name='Name',
            new_name='location',
        ),
    ]
