# Generated by Django 3.2.8 on 2022-03-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtravelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.EmailField(max_length=200, null=True)),
                ('Phone', models.IntegerField(null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('username', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='contactdb',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contactdb',
            old_name='message',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='contactdb',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='contactdb',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='contactdb',
            old_name='subject',
            new_name='Subject',
        ),
    ]
