# Generated by Django 3.2.8 on 2022-03-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtravelapp', '0003_auto_20220301_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdb',
            old_name='Phonenumber',
            new_name='phonenumber',
        ),
    ]
